{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ape-2026.fullname" . }}-api
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ape-2026.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  {{- with .Values.api.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "ape-2026.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
{{- end }}
