apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ape-2026.labels" . | nindent 4 }}
data:
  POSTGRES_HOST: {{ include "ape-2026.postgresql.host" . | quote }}
  POSTGRES_PORT: {{ .Values.configMaps.api.POSTGRES_PORT | quote }}
  POSTGRES_DB: {{ .Values.postgresql.auth.database | quote }}
  REDIS_HOST: {{ include "ape-2026.redis.host" . | quote }}
  REDIS_PORT: {{ .Values.configMaps.api.REDIS_PORT | quote }}
  NEO4J_URI: {{ include "ape-2026.neo4j.uri" . | quote }}
